package com.hc;
// Generated 2017-12-10 15:16:21 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CmsCustomer generated by hbm2java
 */
@Entity
@Table(name = "cms_customer", catalog = "md_yuqiing")
public class CmsCustomer implements java.io.Serializable {

    private Integer customerId;
    private String name;
    private String webUrl;
    private String weixinName;
    private int areaId;
    private String code;
    private Boolean clearance;
    private String remarks;
    private int status;
    private int siteId;

    public CmsCustomer() {
    }

    public CmsCustomer(String name, String webUrl, String weixinName, int areaId, String code, int status, int siteId) {
        this.name = name;
        this.webUrl = webUrl;
        this.weixinName = weixinName;
        this.areaId = areaId;
        this.code = code;
        this.status = status;
        this.siteId = siteId;
    }

    public CmsCustomer(String name, String webUrl, String weixinName, int areaId, String code, Boolean clearance,
            String remarks, int status, int siteId) {
        this.name = name;
        this.webUrl = webUrl;
        this.weixinName = weixinName;
        this.areaId = areaId;
        this.code = code;
        this.clearance = clearance;
        this.remarks = remarks;
        this.status = status;
        this.siteId = siteId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "customer_id", unique = true, nullable = false)
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "web_url", nullable = false, length = 1024)
    public String getWebUrl() {
        return this.webUrl;
    }

    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl;
    }

    @Column(name = "weixin_name", nullable = false, length = 200)
    public String getWeixinName() {
        return this.weixinName;
    }

    public void setWeixinName(String weixinName) {
        this.weixinName = weixinName;
    }

    @Column(name = "area_id", nullable = false)
    public int getAreaId() {
        return this.areaId;
    }

    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }

    @Column(name = "code", nullable = false, length = 200)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "clearance")
    public Boolean getClearance() {
        return this.clearance;
    }

    public void setClearance(Boolean clearance) {
        this.clearance = clearance;
    }

    @Column(name = "remarks")
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "status", nullable = false)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Column(name = "site_id", nullable = false)
    public int getSiteId() {
        return this.siteId;
    }

    public void setSiteId(int siteId) {
        this.siteId = siteId;
    }

}
